TOLK-18 oversikt over oppdrag i kalender
navikt/crm-hot-tolk pull request #2075
Opened 2024-09-30 12:05 UTC by AndreMarthinsen

Første versjon av komponent for frilanstolk-kalender. Relevant kode kan finnes i force-app/main/freelanceCalendar, samt noen endringer i freelanceCommunity. Resten er statiske ressurser fra FullCalendar.

2024-09-30 12:09 UTC, Nirajalale approved these changes

2024-10-01 08:10 UTC, EdvardBrekke commented on .forceignore
Tror ikke denne skal endres

2024-10-01 08:14 UTC, EdvardBrekke commented on force-app/main/default/staticresources/FullCalendar/locales/af.js
Moet dit worden opgenomen?

2024-10-01 08:22 UTC, EdvardBrekke reviewed
Må alle språkfilene og den ene binærfilen under MACOSX være med?

2024-10-01 09:52 UTC, EdvardBrekke commented on force-app/unpackagable/community/networks/Tolketjenesten.network-meta.xml
> +        <profile>Admin</profile>
Er det case sensivit eller går dette fint?

2024-10-01 09:53 UTC, EdvardBrekke commented on force-app/main/default/audience/Default_Tolketjenesten.audience-meta.xml
> +</Audience>
Denne filen må heller ikke med

2024-10-01 09:54 UTC, EdvardBrekke requested changes
Vennligst se kommentarer :)

2024-10-01 11:20 UTC, MathiBK commented on force-app/unpackagable/community/networks/Tolketjenesten.network-meta.xml
> +        <profile>Admin</profile>
endret det tilbake til sånn det var

2024-10-01 11:20 UTC, MathiBK commented on force-app/main/default/audience/Default_Tolketjenesten.audience-meta.xml
> +</Audience>
Den er nå borte vekk :)

2024-10-02 05:47 UTC, EdvardBrekke approved these changes
Be gjerne Carl se over også 😃👍🏻

2024-10-02 16:50 UTC, chfosli approved these changes
Ser bra ut.

En liten kommentar; om det dere har lagt i staticresources-mappa kun skal brukes i kalenderen, kan kanskje det også flyttes til freelanceCalendar-mappa?

2024-10-03 10:20 UTC, merged