TOLK-2182 Feil med vedlegg
navikt/crm-hot-tolk pull request #2130
Opened 2024-11-12 13:00 UTC by its-me2000

HOT_Request vedlegg ikke synlig for bruker hvis Orderer__c != bruker account. Og bruker kan ikke laste opp filene.

2024-12-16 13:53 UTC, chfosli requested changes

2024-12-16 13:53 UTC, chfosli commented on force-app/main/triggers/triggers/ContentVersionTrigger.trigger
> +trigger ContentVersionTrigger on ContentVersion(
Jeg tenker denne bør flyttes hit: https://github.com/navikt/crm-platform-base/tree/main/force-app/main/default/triggers

2024-12-16 13:53 UTC, chfosli commented on force-app/main/userCommunity/lwc/mineBestillingerWrapper/mineBestillingerWrapper.html
> +                ></c-record-files-without-sharing>
Hvis man bruker without-sharing er det viktig å sjekke tilganger i controller-klassen før man retuernerer data til lwc. Inputen fra lwc'en kan manipulertes og bør ikke stoles på.

2025-06-25 06:22 UTC, its-me2000 commented on force-app/main/userCommunity/lwc/mineBestillingerWrapper/mineBestillingerWrapper.html
> +                ></c-record-files-without-sharing>
har lagt til tilgangssjekk til without-sharing lwc https://github.com/navikt/crm-community-base/pull/394

2025-06-25 06:27 UTC, its-me2000 commented on force-app/main/triggers/triggers/ContentVersionTrigger.trigger
> +trigger ContentVersionTrigger on ContentVersion(
trigger flyttet https://github.com/navikt/crm-platform-base/pull/780

2025-06-25 06:29 UTC, chfosli approved these changes

2025-06-25 11:09 UTC, merged